### ISSUE TITLE
QA - Login - Wrong alert message displayed while login.

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#247]
I have given invalid password for the valid user id but system shows tick mark on the password and then after submitting application display "Some server error occurred"
![password message](https://user-images.githubusercontent.com/34448885/35861905-d08e2e7c-0b6f-11e8-9b7f-6575ca27a834.jpg)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by acharotariya** [comment]
Still right mark is display but error message change "Error: password doesn't match"

**Comment by fsaiyedOB** [comment]
@acharotariya , the tick mark is non-empty input async validator. This doesn't validate email/password from the server.

**Comment by qajha** [comment]
Issue is resolved now
