### ISSUE TITLE
QA-Forget password-Password reset field not showing proper message.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#248]
When  user not entered the reset password field and then click on Reset  button system is showing improper Error message"Please Enter all  Fields".

1.Enter the URL
2.Click on Forgetten Password?
3.Not fill the Registered Email id
4.Click on Reset button

**Comment by fsaiyedOB** [comment]
fixed.

**Comment by acharotariya** [comment]
"Please enter your registered email" This message is display now.
