### ISSUE TITLE
QA - Sign Up - Wrong alert message is displayed while sign up with already registered email id.

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#250]
![wrong validation message](https://user-images.githubusercontent.com/34448885/35863226-0ec76a42-0b74-11e8-8dc4-47e0e88d3e3b.png)

**Comment by fsaiyedOB** [comment]
Login service response showed in the alert message.

**Comment by acharotariya** [comment]
Its working fine now.
