### ISSUE TITLE
QA - Social media logins not working and no tool tip for any icons under login.

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#251]
Login not working for the below social media icons.
1. Facebook
2. Google Plus
3. Twitter
4. Linkedin
5. LDAP

**Comment by fsaiyedOB** [comment]
Social login fixed. Added tootips.

**Comment by acharotariya** [comment]
When User trying login with Social Media its not working and "This site can’t be reached" page found.
![page is not working page found when user trying to login with social media](https://user-images.githubusercontent.com/28082572/36464357-77055fe2-16f5-11e8-8644-d7232e327bbe.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
