### ISSUE TITLE
QA-Home Page-When user delete the folder page layout/pages and partial section then how to create the new folder in website builder

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#262]
When user delete the folder page layout/pages and partial section then how to create the new folder in website builder.

Steps to reproduce
1.Enter the URL:https://www.webbuilder.qaflowz.tk
2.Login to system
3.Create the website
4.Expance the website folder
5.Delet the folders.

**Comment by fsaiyedOB** [comment]
These are required folders. Delete option is removed.

**Comment by acharotariya** [comment]
Done.
Delete option is not available for the required Folders.
