### ISSUE TITLE
QA - Pages - Static pages when i click settings then component settings went down.

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#263]
1. Login into the system
2. Under the pages, i have created a new page and when i click settings and try to add\modify\font size changes then the component settings presented at the left bottom and not visible to the user.
![component settings](https://user-images.githubusercontent.com/34448885/35916907-0a3caadc-0c32-11e8-9313-032d42f854e8.png)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by acharotariya** [comment]
Its working properly now.
