### ISSUE TITLE
QA - Partials - Count mismatch between partials and dashboard.

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#268]
1. Login into the system. 
2. Create 1 or 2 pages.
3. Click on the project name and verify the count under partials.
4. Verify the count under the Partials submenus which shows 4.

refer the screen shots.
![count mismatch](https://user-images.githubusercontent.com/34448885/35920454-e933c274-0c3d-11e8-8167-a1db93335154.jpg)

**Comment by fsaiyedOB** [comment]
Fixed

**Comment by acharotariya** [comment]
Count is Update now.
