### ISSUE TITLE
QA-Firefox Browser Issue-When we login into system and expands the partial folder and select the file then system is showing delete option two times.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#271]
When we login into the system and expands the partial folder and select the file then system is showing delete option two times.

1.Login into application
2.Create the Website
3.Expands the folder option
4.Select the Folder in List view

![firefox browser](https://user-images.githubusercontent.com/36195435/35965650-93da0eec-0ce1-11e8-9051-1879be80cedd.png)

**Comment by fsaiyedOB** [comment]
Checked in Firefox. Icons are fixed

**Comment by qajha** [comment]
Issue is resolved now in QA server
