### ISSUE TITLE
QA - Components - text overlapping

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/website-builder#272]
![overlapping](https://user-images.githubusercontent.com/34448885/35965906-48b205d6-0ce2-11e8-8d44-2a169155c5c1.jpg)

**Comment by mohit5540** [comment]
this will not occur in higher resolution.

**Comment by gkumar9** [comment]
The minimum resolution supported for UI is 1366x768. Or you can just close the sidebar to view UI properly.

**Comment by qajha** [comment]
As per development comment I have closed this ticket
