### ISSUE TITLE
QA-Layout Section-When we create the new Layout its not showing in layout list.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#273]
When we create the new Layout its not showing in layout list.

Steps to reproduce
1.Login into system
2.Create the Website
3.Create the new layout
4.Go to Layout list its not showing.
![layout issue](https://user-images.githubusercontent.com/36195435/35968214-390ed030-0ce9-11e8-9a98-ff9fc3ed40a7.png)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by acharotariya** [comment]
Still List not updated.
![list not updated yet](https://user-images.githubusercontent.com/28082572/36462510-e423aad6-16e9-11e8-8f43-96eb64e59c32.jpg)
