### ISSUE TITLE
QA- Suggestion-  increase size of component in open style manager.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#274]
we can not properly increase or decrease the value in selected box.
![012ace52434b4a97a16ea0475864d085](https://user-images.githubusercontent.com/28082572/35968093-df9d7682-0ce8-11e8-97c4-be506c2bfed3.jpg)

**Comment by fsaiyedOB** [comment]
Fixed

**Comment by qajha** [comment]
Done
