### ISSUE TITLE
QA-Pages Section-When user delete the pages from existing template which is imported from Project setting then those page is not match with page list.refer attachment.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#275]
When a user deletes the pages from existing template which is imported from Project setting then those page is not matched with page list.refer attachment.

Steps to Reproduce
1.Login into system
2.Create the Website
3.Go to Project settings>Select the existing template>Added the template with pages
4.Delete the pages.
![pagelist issue](https://user-images.githubusercontent.com/36195435/35969692-b2c89452-0ced-11e8-8632-ad09c586bf58.png)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by qajha** [comment]
Issue is resolved now in QA server
