### ISSUE TITLE
QA-Firefox Browser-In Firefox browser Designed Form component image is not loaded properly.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#277]
In Firefox browser Designed Form component image is not loaded properly in all images components.

Steps to Reproduce
1.Login into Application in FireFox browser(58 version)
2.Go to Component Section
3.Select the Designed form component in page level.
![designed forms](https://user-images.githubusercontent.com/36195435/35972380-9e0e67c6-0cf7-11e8-9b9f-c3cbde68a0ad.png)

**Comment by fsaiyedOB** [comment]
Fixed the images of components in firefox .

**Comment by fsaiyedOB** [comment]
Fixed the images of components in firefox .

**Comment by qajha** [comment]
Issue is resolved now in QA server
