### ISSUE TITLE
QA - select background image  section -  how can user identify to add image??

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#281]
validation necessary for add new image to the list and select particular image to the their website.

![83c43a9c14fa4c898ec1da0e9b53e5d1](https://user-images.githubusercontent.com/28082572/35973253-c21810e2-0cfa-11e8-8728-877eb40c5993.jpg)

**Comment by fsaiyedOB** [comment]
Image thumbnail and image name is shown. So the user can identify the image he/she wants to use. There can't be any validation in images.
