### ISSUE TITLE
QA-Page Section-When we use the existing template then page section list view the rows are outside the page and not display properly.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#282]
When we use the existing template then page section list view the rows are outside the page and not display properly.

Steps to Reproduce
1.Login into website builder
2.Create the Existing template with website
3.Go to pages section in page List view part
4.Check S No 7 and 8
![page list outpage](https://user-images.githubusercontent.com/36195435/35974652-f30fc104-0cff-11e8-9d86-6409fa383520.png)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by qajha** [comment]
Issue is resolved now in QA server
