### ISSUE TITLE
QA - 1 column component section - inner component (ex. background image) overlap to another section.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#283]
when select 1 column component and add background image and its overlap to diffrent  section. 

![1ce7e94a8248405dbc5731e8ddae7c92](https://user-images.githubusercontent.com/28082572/35974746-54a4c75c-0d00-11e8-96b1-67ca492766f8.jpg)

**Comment by fsaiyedOB** [comment]
Specify different class to you block and then apply styles. Same classes will override everywhere. Here you will have .row class same.

**Comment by acharotariya** [comment]
thanks..it's working...!!
