### ISSUE TITLE
QA-Footer Componets-When we drag and drop the Style 8, 9 and Style 10 then those component is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#284]
When we drag and drop the Style 8,9 and Style 10 then those component is not working.

Steps to Reproduce
1.Login into the system.
2.Go to Footer component
3.Drag and Drop the Style 9 and Style 10 component

**Comment by HarshOB** [comment]
There is HTML problem (Grapes Parsing actually) in such component then we are removing that component from the list.

**Comment by qajha** [comment]
Style 2,Style 4,Style 6,Style 7,Style 9,Style 10 those style is not working and some style is working fine in previlously.

**Comment by fsaiyedOB** [comment]
Removed non-working components

**Comment by qajha** [comment]
Style 4,Style 5,Style 7 is not working

**Comment by qajha** [comment]
Style 4 and Style 5 is not working

**Comment by qajha** [comment]
Style 6 and Style 7 is not working

**Comment by qajha** [comment]
Issue is resolved now in QA server
