### ISSUE TITLE
QA-Header Component-When we drag and drop the style 5 and Style 10,11 is not working

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#285]
When we drag and drop the style 5 and Style 10,11 is not working and system is also showing Error in console window "Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]
move @ grapes.min.js:2
endMove @ grapes.min.js:2"

Steps to Reproduce
1.Login into the system.
2.Go to Component section
3.Drag and drop the style 5 and Style 10,11

**Comment by HarshOB** [comment]
There is HTML problem (Grapes Parsing actually) in such component then we are removing that component from the list.

**Comment by qajha** [comment]
Again 10,11 and 9 is not working.

**Comment by fsaiyedOB** [comment]
Removed non-working components

**Comment by qajha** [comment]
Issue is resolved now in QA server
