### ISSUE TITLE
QA - form section - basic form is not displaying properly.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#288]
form section is not in proper format and styling.ex. checkbox label displaying below checkbox.
![b18db351cc6f499dbf46359d5c61fd84](https://user-images.githubusercontent.com/28082572/36017320-3ef431ac-0d9d-11e8-951f-ef3dac77b251.jpg)

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by qajha** [comment]
Need to add CSS from page settings. please discuss for this.

**Comment by gkumar9** [comment]
Done. 
![screenshot from 2018-03-12 16-14-05](https://user-images.githubusercontent.com/33317261/37279313-71a6a2de-2610-11e8-8a85-fcbdace91e8a.png)

**Comment by qajha** [comment]
Issue is resolved now in QA server
