### ISSUE TITLE
QA-Global variable-When we used the global variable and doing some change and then delete the component,when we publish the website the global variable is still showing.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#289]
When we used the global variable and doing some change and then delete the component when we publish the website the global variable is still showing.
![global variable](https://user-images.githubusercontent.com/36195435/36018808-1a1f223c-0da3-11e8-97c4-6dd1abe24998.png)

**Comment by fsaiyedOB** [comment]
Global variable will not be shown if you remove the component from the page. Please hard refresh the page.

**Comment by acharotariya** [comment]
not working....if i simply use this functionality..!!

**Comment by qajha** [comment]
Issue is closed now.
