### ISSUE TITLE
QA-Publish Website-After publishIf user delete the signup page from existing template and again publish the website system is still showing signup page in front end.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#290]
When we used the existing template for a newly created website and publish the website and user is decided to delete the signup page from page section folder and deleted the Signup page and published the website again then the system is still showing the Signup page.

**Comment by fsaiyedOB** [comment]
Fixed the issue. Now after deleting, the page is not shown.

**Comment by qajha** [comment]
Issue is resolved now in QA server
