### ISSUE TITLE
QA-Project Setting-Commit project feature is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#291]
When we doing some changes in pages and then we decided to commit the change in Github, we go in project setting page commit then those commit is not showing.

Spets to reproduce
1.Login into Application
2.Create the Website with existing user.
3.Changes some information in pages
4.Go to Project Setting>Enter the commit change>Click on Commit project setting.

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by qajha** [comment]
Issue is resolved now in QA server
