### ISSUE TITLE
QA- custom form controls section -  full form is not in proper format and styling.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#295]
![420bfaa0e1cc43ecbd82fc9bfdbefb8a](https://user-images.githubusercontent.com/28082572/36023107-5a73035e-0db1-11e8-804b-130736fdb10f.jpg)

**Comment by fsaiyedOB** [comment]
Styling and formatting is not required for this component.

**Comment by qajha** [comment]
As per mention comment by devloper I have close this ticket.
