### ISSUE TITLE
QA-Create Website-When user click on create website icone and enter the website name and click on multiple times in create project button  then system created the multiple website for same name.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#296]
When the user clicks on create website icon and enter the website name and click on multiple times in create project button then system created the multiple websites for the same name.
![samename](https://user-images.githubusercontent.com/36195435/36023614-066e6dbe-0db3-11e8-80d8-8de673a3b72e.png)

**Comment by fsaiyedOB** [comment]
Fixed multiple project issue

**Comment by qajha** [comment]
Issue is closed now
