### ISSUE TITLE
QA - special component section - accordion section fix the arrow button issue.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#298]
![1fe987ca2c18472f8d2d4e579270b42a](https://user-images.githubusercontent.com/28082572/36023886-fb8bf208-0db3-11e8-9264-7bfad10ae8ac.jpg)

**Comment by HarshOB** [comment]
Remove arrow button that was generated by some CSS

**Comment by qajha** [comment]
Issue is resolved now in QA server...
