### ISSUE TITLE
QA-Dashboard-Login to site builder, it will land to website creator, go to dashboard then again go back to website editor / creator and try to select different template. - it does not work.    Post this action it stops at all although we re-login. workaround: it works if you refresh the site.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#303]
Login to site builder, it will land to website creator, go to dashboard then again go back to website editor / creator and try to select different template. - it does not work.
   Post this action it stops at all although we re-login. workaround: it works if you refresh the site.

**Comment by fsaiyedOB** [comment]
Resolved.

**Comment by qajha** [comment]
Issue is resolved now in QA server
