### ISSUE TITLE
QA-Website builder-Multiple folder is created when user click on multiple times in create button in partial folder creation times.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#305]
Multiple folders is created when user click on multiple times in create a 
![foldercreated](https://user-images.githubusercontent.com/36195435/36026571-c3f9e48a-0dbd-11e8-90d8-b582521bf1fb.png)
button in partial folder option is choose.

Steps to Reproduce
1.Login into System
2.Create the Website
3.Go to Folder section
4.Create the Folder and enter the Name"Test12" and click on multiples times in create button.

**Comment by fsaiyedOB** [comment]
Validation added if folder already exist.

**Comment by qajha** [comment]
Issue is reopen and Folder is created inside the folder with Same name refer attached screenshots

**Comment by fsaiyedOB** [comment]
UI bug. Folder is not actually created. It is not shown after the tree is updated or refreshed.

**Comment by qajha** [comment]
Issue is resolved now in QA server
