### ISSUE TITLE
QA-Website builder-When we click on delete icon in partial sub folder the system is showing wrong tooltip name "Delete file" in places of "Delete folder".

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#306]
When we click on delete icon in partial subfolder the system is showing wrong tooltip name "Delete file" in places of "Delete folder".
![delete tooltip](https://user-images.githubusercontent.com/36195435/36027528-a2bb319e-0dc1-11e8-8e39-ffea09cf4e2a.png)

**Comment by fsaiyedOB** [comment]
Resolved

**Comment by qajha** [comment]
Its working fine in QA server.
