### ISSUE TITLE
QA-Website builder-Wrong project name is showing in Partial List with respect to proper name in project setting field.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#308]
The wrong project name is showing in Partial List/Pages List/Layout List with respect to a proper name in project setting field .Project Name in Partial List "3c926153-e935-4e89-b914-3e240b0cbe57 and Website list its showing like "123456789" Refer Attachment

![projectname](https://user-images.githubusercontent.com/36195435/36029896-1a66a58a-0dcb-11e8-8827-dd6625784d73.png)

**Comment by fsaiyedOB** [comment]
Resolved .

**Comment by acharotariya** [comment]
ok..it's working fine..!!
