### ISSUE TITLE
QA-Project Setting-When we click on Custom Domain radio button no any operation is performed.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#309]
When we click on Custom Domain radio button no any operation is performed "
vendor.d95e000….js:139827 GET https://ws.qaflowz.tk:4032/socket.io/?EIO=3&transport=polling&t=M5woetO net::ERR_CONNECTION_REFUSED
Request.create @ vendor.d95e000….js:139827
Request @ vendor.d95e000….js:139728
XHR.request @ vendor.d95e000….js:139655
XHR.doPoll @ vendor.d95e000….js:139685
Polling.poll @ vendor.d95e000….js:71503
Polling.doOpen @ vendor.d95e000….js:71448
Transport.open @ vendor.d95e000….js:29626
Socket.open @ vendor.d95e000….js:138820
Socket @ vendor.d95e000….js:138694
Socket @ vendor.d95e000….js:138603
Manager.open.Manager.connect @ vendor.d95e000….js:72268
(anonymous) @ vendor.d95e000….js:72582"

![custom domain field](https://user-images.githubusercontent.com/36195435/36030341-cee1243a-0dcc-11e8-8fe3-18edc5035c71.png)

**Comment by fsaiyedOB** [comment]
Reproduced the case. Custom domain radio is working fine.

**Comment by qajha** [comment]
Its working fine now may be that Issue is comes due to API is not worked at that time
