### ISSUE TITLE
QA-Website builder-When user clone the existing website then system is generated the duplicate name for clone website.refer attachment 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#310]
When user clone the existing website then system is generated the duplicate name for clone website

Steps to reproduce
1.Login into System.
2.Create the Website "Test"
3.Create the clone for exisiting website 
![clone website](https://user-images.githubusercontent.com/36195435/36085597-c244a7fc-0fec-11e8-9c5e-15439879076f.png)

**Comment by fsaiyedOB** [comment]
Incremental name will be added in the next update.

**Comment by qajha** [comment]
Issue is resolved now in QA server
