### ISSUE TITLE
QA - Website Builder - File or Tab Not Closed Some Times.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#311]
Create new Website.
Click on Layout Folder.
Open Any file.
Close that file from the dashboard.
![file or tab not closed some times](https://user-images.githubusercontent.com/36226408/36085737-0cbd8c4e-0fee-11e8-8e9e-3b156649aaaa.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
