### ISSUE TITLE
QA - Website Builder - File List not updated in list section of the page in layout, Pages and partials.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#312]
Create Project.
Click on Add new Layout options.
Create new layout.
Observe Layout list not updated in besides.
![file name not updated in list section of the page](https://user-images.githubusercontent.com/36226408/36087037-f622ad68-0ff5-11e8-82d3-7fd2fd28d222.jpg)

**Comment by fsaiyedOB** [comment]
New page is reflecting in PageStats

**Comment by acharotariya** [comment]
Still its not update properly.

After Add New File Only Side Menu get refresh but Page section is not refresh.
Page section also need to refresh.

**Comment by fsaiyedOB** [comment]
All satus page now show proper listing.

**Comment by qajha** [comment]
if user delete the file something then the system is automatically refreshing but right now user have to reload the page this is not correct process.

**Comment by fsaiyedOB** [comment]
Updated the status pages when user creates new file or add new partial

**Comment by qajha** [comment]
Issue is resolved now in QA server
