### ISSUE TITLE
QA - Website Builder - Layout - Default Layout - Double Dropdown display in Header.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#313]
![double dropdown display in header](https://user-images.githubusercontent.com/36226408/36087135-b1538d64-0ff6-11e8-905a-02665c80cba5.jpg)

**Comment by fsaiyedOB** [comment]
All action button in layout editor are removed.

**Comment by acharotariya** [comment]
Action Buttons are removed.
