### ISSUE TITLE
QA -  browser compatibility issue - page creating functionality is not working & some time after refresh page is working.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#314]
i'm currently creating new page in pages section but not created in below listed browser.

Mozilla Firefox 58.0.2
Google Chrome 61.0.3163.79

**Comment by fsaiyedOB** [comment]
Page creation is working fine in Mozilla Firefox 58.0.2 and Google Chrome: 64.0.3282.167
