### ISSUE TITLE
QA - Website Builder - Layout - Default Layout - File tab missing when click on main website option.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#315]
Create Project.
Click on default Layout.
Now click on main website option.
Observe File Tab Header is missing.

![file tab missing when user click on main website option](https://user-images.githubusercontent.com/36226408/36087752-ea74acb0-0ff9-11e8-9a7b-806201876569.jpg)

**Comment by Nikunj025** [comment]
Create Project.
Click on default Layout.
Now click on main website option.
Observe File Tab Header is missing.

**Comment by fsaiyedOB** [comment]
Only the editor and settings page are kept in tabs.

**Comment by acharotariya** [comment]
Still Not resolved.

**Comment by fsaiyedOB** [comment]
Only the editor pages are kept in tabs. Do not click on blank white space in tree nodes. Click on the text in tree nodes.

**Comment by qajha** [comment]
We need to discuss with Mohit on Monday regarding this ticket

**Comment by gkumar9** [comment]
Currently tabs have been not used, hence issue is invalid. Cant reproduce.

**Comment by qajha** [comment]
I have close this Issue due to Tab functionality is remove from the website builder.
