### ISSUE TITLE
QA - Website Builder - Layout - Default Layout - File Display HTML Content when User click on Save option From header dropdown.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#316]
Create Project.
Click on Layout Folder.
Open Default Layout.
Update Layout.
Click on Save option From Header Dropdown.
![file display html content when user click on save option from header dropdown 1](https://user-images.githubusercontent.com/36226408/36087720-d5ff3a0c-0ff9-11e8-940a-dc84a5c9135f.jpg)
![file display html content when user click on save option from header dropdown 2](https://user-images.githubusercontent.com/36226408/36087721-d63c57fc-0ff9-11e8-8dbf-6b3d822440aa.jpg)

**Comment by fsaiyedOB** [comment]
Removed the action buttons. Use save button in the footer to save files.

**Comment by acharotariya** [comment]
Done Action Buttons removed.
