### ISSUE TITLE
QA - Website Builder - Layout - Default Layout - Layout Section Should not be Blank if User Click on reset option From Header Dropdown.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#317]
Create Project.
Click on Layout Folder.
Select Default Layout.
Add or Update Layout.
Now Click on Reset option from Header Dropdown.
Layout should not be Blank, its should be reset with default Grid.

![layout section should not be blank if user click on reset option from header dropdown 1](https://user-images.githubusercontent.com/36226408/36087880-9cfe017e-0ffa-11e8-8b9e-679febd78b08.jpg)
![layout section should not be blank if user click on reset option from header dropdown 2](https://user-images.githubusercontent.com/36226408/36087881-9d3b2a4a-0ffa-11e8-82f9-825b845db40b.jpg)

**Comment by fsaiyedOB** [comment]
Remove the actions buttons.
