### ISSUE TITLE
QA - Website Builder - Layout - Default Layout Grid should be display if user create new Layout.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#318]
Create Project.
Click on Layout Folder.
Click on New Layout Option and Create new Layout.
Click on Newly Created Layout.
Observe No Default Grid is display in besides.

![default layout grid should be display if user create new layout](https://user-images.githubusercontent.com/36226408/36087993-4c81df58-0ffb-11e8-85c1-e13a87c80f45.jpg)

**Comment by fsaiyedOB** [comment]
A new layout will be blank. The user will create layout as per need. We are providing default layout for general use.

**Comment by acharotariya** [comment]
Got it.
