### ISSUE TITLE
QA-Website Builder-When we create the file in menu folder in partial section with "Test" name and then delete the same field and again create the file with same name then system is showing Error message "File already exists"

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#319]
When we create the file in menu folder in partial section with "Test" name and then delete the same field and again create the file with the same name then system is showing Error message "File already exists"

1.Login into System.
2.Create the Website
3.Expand the Tree View
4.Go to PArtial folder>Select the Menu folder>Create the Field>Enter the "Test" name and delete the File>again create the file with same name

**Comment by fsaiyedOB** [comment]
Fixed

**Comment by qajha** [comment]
Issue is resolved now in QA server
