### ISSUE TITLE
QA-Website builder-In menu folder if user mention the file name "pages" and create the file and then delete that file and go to pages section and create the new file then system is showing same name still in file name field.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#320]
In menu folder, if user mentions the file name "pages" and create the file and then delete that file and go to pages section and create the new file then the system is showing the same name still in file name field.

Steps to Reproduce

1.Login into system
2.Create the Website
3.Go to Menu option in partial holder
4.Create the File in menu option
5.Go to Pages section>Click on Click file new option

**Comment by fsaiyedOB** [comment]
Fixed.

**Comment by acharotariya** [comment]
working fine..!!
