### ISSUE TITLE
QA - Website Builder - Pages - Site not Published Page Display when user click on Website preview Option From Site bar.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#323]
Create New Project.
Add any Page in Pages Folder.
Now Click on Website Preview Option From Sidebar.
Observe That it gives error for All Pages.

![site not published page display when user click on website preview option from site bar](https://user-images.githubusercontent.com/36226408/36089588-af46f82e-1002-11e8-8da7-cf9015696b09.jpg)

**Comment by gkumar9** [comment]
Yes. This will be shown as you have not published the site. Just adding the page won't reflect. You have to publish first.

**Comment by acharotariya** [comment]
Done.
Its working Fine.
