### ISSUE TITLE
QA - Website Builder - Multiple Alert message should not be display in All Error Message and Success Message.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#324]
Create New Project.
Again Create Project With Same name with Multiple Click on Create Project Button.
Observe Multiple Alert Message Display in Top.

![multiple alert message should not be display](https://user-images.githubusercontent.com/36226408/36089918-2f9899aa-1004-11e8-9fd2-db0fa7a776b0.jpg)

**Comment by fsaiyedOB** [comment]
Yes it will come, as it is blocking you for creating new site with same name

**Comment by acharotariya** [comment]
still not resolved yet.
it should be display only one time.

**Comment by fsaiyedOB** [comment]
Yes it will display multiple times as long as you do multiple clicks

**Comment by qajha** [comment]
As discussed please showing the message in single times.

**Comment by brgurur** [comment]
Not an issue.
