### ISSUE TITLE
QA - partial - can't change partial.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#327]
steps:
1. go to partial section.
2. create new partial.
3. go to page section and create new page.
4. go to that page setting and change default partial header to my custom partial header and save it.
5. after show my preview it can't change anything.

**Comment by fsaiyedOB** [comment]
The layout used in .layout file should contain that newly created partial. Then an only then you can use that partial. Else use ReUse component.

**Comment by acharotariya** [comment]
ok..it's working..thanks.
