### ISSUE TITLE
QA - Website Builder - User Not able to close alert message and also page is not responding.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#333]
Create project.
apply any Template from Project Setting.
Now Open Multiple partial files.
Change only Tab without updating data.

![user not able to close alert message and also page is stucked](https://user-images.githubusercontent.com/36226408/36097009-f06bb22e-101e-11e8-8ef1-bd8afc30381b.jpg)

**Comment by fsaiyedOB** [comment]
Reproduced the test case, no errors were found.

**Comment by fsaiyedOB** [comment]
Tabs are removed for now.

**Comment by qajha** [comment]
Due to Tab remove we have close this ticket

**Comment by qajha** [comment]
closed Issue
