### ISSUE TITLE
QA - Wesite Builder - Images are not display after apply Template in Project From Project Setting.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#334]
Create project.
apply Template 2 from Project Setting.
Click on Partial Folder.
Go to Compare Folder.
Click on List Partial.
Images not display through out Site.

![images are not display after apply template in project](https://user-images.githubusercontent.com/36226408/36097172-bf23a9be-101f-11e8-9442-384c32fab10b.jpg)

**Comment by fsaiyedOB** [comment]
This image will come from PDM api after you configure api urls when using E-Commerce components.

**Comment by acharotariya** [comment]
where to configure?how we can use?provide steps.

**Comment by mohit5540** [comment]
product images do not display/configure inside webbuilder. api urls can be configured from settings.

**Comment by qajha** [comment]
As per develoment comment I have closed this ticket
