### ISSUE TITLE
QA - page setting section - add tooltip.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#335]
steps:
1.go to page settings > add local script .
2.go to page settings > add local styles .
![flowz builder the next generation dynamic website builder 2](https://user-images.githubusercontent.com/28082572/36097189-d3b14580-101f-11e8-9e53-ff55dae03251.png)

**Comment by fsaiyedOB** [comment]
Added tooltip

**Comment by acharotariya** [comment]
add tooltip here also.
project settings -> external links
project settings -> global styles
project settings -> global scripts
project settings -> payment gateway
![flowz builder the next generation dynamic website builder 7](https://user-images.githubusercontent.com/28082572/36631128-4c7114b0-1998-11e8-8da7-b1d59308d120.png)
