### ISSUE TITLE
QA - Website Builder - Invalid Token Error Display Sometimes when User Click on Preview Button.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#338]
Create Project.
Create Multiple Partial in That Project.
Now Go to Project Setiing.
Apply Template 2 on that Project.
Now Go to Pages Folder.
Expand Taht Folder and Click on AddressBook List Page.
Click on Preview Button of That Page.

![invalid token error display sometimes when user click on preview button](https://user-images.githubusercontent.com/36226408/36132573-2efbc842-109e-11e8-96c9-2c871ae5b2ba.jpg)

**Comment by fsaiyedOB** [comment]
After selecting template 2, you are missing one more step: In project settings only, > import plugins > click refresh button. It will work proper.

**Comment by qajha** [comment]
Issue is resolved now in QA server
