### ISSUE TITLE
QA - Website Builder - User can not be able to rename project name Sometimes.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#340]
Create Project as AAA.
Create Another project as BBB.
Click on Project Setting of BBB.
Change Project Name as ABC.
Save Updated Setting.
After Saving Observe That Project Name AAA is Change Instead of BBB.
Issue Demo is given to Mohit Shah and Faizan Saiyed.

**Comment by mohit5540** [comment]
check rename for multiple website

**Comment by fsaiyedOB** [comment]
Checked the test case. No issue found.

**Comment by qajha** [comment]
Issue is resolved now in QA server
