### ISSUE TITLE
QA-Website Builder-When user using the existing template and then publish the website and user decided to change some things in pages for using reused component and save the pages then those change is reflect in front end website. 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#342]
When user using the existing template and then publish the website and user decided to change some things in pages for using reused component and save the pages then those change is reflect in front end website before publish as per requirement after publish the website then changes is reflect on.

**Comment by qajha** [comment]
When user using the existing template and then publish the website and user decided to change some things in pages for using reused component and save the pages then those change is reflect in front end website  before publish as per requirement after publish the website then changes is reflect on.

**Comment by fsaiyedOB** [comment]
Saving the file won't reflect in the frontend. Only Preview Page and Default Publish will reflect.

**Comment by qajha** [comment]
Issue is resolved now and working fine in QA server...
