### ISSUE TITLE
QA-Website builder-When user using the existing template and then publish the website and user decided to change some things in pages for using reused component and click on preview button then those change is reflect in front end website before publish as per requirement after publish the website then changes is reflect on.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#343]
When user using the existing template and then publish the website and user decided to change some things in pages for using reused component and click on preview button then those change is reflect in front end website before publish as per requirement after publish the website then changes is reflect on.

**Comment by fsaiyedOB** [comment]
Resolved.

**Comment by qajha** [comment]
Issue is resolved now.
