### ISSUE TITLE
QA - designed form section - component not viewing as described and drag & drop not working in some component.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#344]
![desktop screenshot](https://user-images.githubusercontent.com/28082572/36151740-7ea9a800-10ee-11e8-868e-9db1ecce61b2.png)

**Comment by fsaiyedOB** [comment]
Can you please list the component not getting drag and dropped?

**Comment by acharotariya** [comment]
drage & drop issue:
-------------------------
style 1
style 6
style 7
style 8
style 11 
style 12

component not viewing as described when drag and drop:
-------------------------------------------------
style 2
style 3
style 4
style 5
style 9
style 10

**Comment by fsaiyedOB** [comment]
Issue with the third party froala components. Will fix manually later.

**Comment by fsaiyedOB** [comment]
Removed non-working components. Updated the UI.

**Comment by Nikunj025** [comment]
Done.
Many Components are Removed Now From Side Bar.
