### ISSUE TITLE
QA-IE Browser-Website builder is not working

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#345]
Website builder is not working.

Refresh the page to see messages that may have occurred before the F12 tools were opened. 
SCRIPT438: Object doesn't support property or method 'addEventListener' 
jquery.min.js, line 3 character 147
SCRIPT5009: 'jQuery' is undefined 
jquery-ui.min.js, line 6 character 73
SCRIPT5009: 'jQuery' is undefined 
jquery.slimscroll.min.js, line 8 character 1
SCRIPT5022: Bootstrap's JavaScript requires jQuery 
bootstrap.min.js, line 6 character 31
SCRIPT5007: Unable to get property 'fn' of undefined or null reference 
bootstrap-editable.min.js, line 5 character 4963
SCRIPT438: Object doesn't support property or method 'addEventListener' 
jquery.min.js, line 3 character 147
SCRIPT5009: 'jQuery' is undefined 
jquery-ui.min.js, line 6 character 73
SCRIPT5009: 'jQuery' is undefined 
jquery.slimscroll.min.js, line 8 character 1
SCRIPT5022: Bootstrap's JavaScript requires jQuery 
bootstrap.min.js, line 6 character 31
SCRIPT5007: Unable to get property 'fn' of undefined or null reference 
bootstrap-editable.min.js, line 5 character 4963
SCRIPT1010: Expected identifier 
grapes.min.js, line 2 character 549
SCRIPT1010: Expected identifier 
grapesjs-blocks-basic.min.js, line 2 character 607
SCRIPT1010: Expected identifier 
grapesjs-plugin-forms.min.js, line 2 character 607
SCRIPT5009: 'grapesjs' is undefined 
grapesjs-plugin-export.min.js, line 1 character 483
SCRIPT5009: 'grapesjs' is undefined 
grapesjs-aviary.min.js, line 2 character 486
SCRIPT1002: Syntax error 
grapesjs-preset-webpage.js, line 1 character 60
SCRIPT1010: Expected identifier 
grapesjs-component-countdown.min.js, line 2 character 595
SCRIPT1010: Expected identifier 
grapesjs-navbar.min.js, line 2 character 595
SCRIPT1010: Expected identifier 
grapesjs-blocks-flexbox, line 2 character 644
SCRIPT1010: Expected identifier 
grapesjs-blocks-bootstrap4.min.js, line 2 character 680
SCRIPT1002: Syntax error 
product-plugin.js, line 7 character 1
SCRIPT1028: Expected identifier, string or number 
flowz-blocks.js, line 14 character 7
SCRIPT5009: 'jQuery' is undefined 
select2.min.js, line 1 character 153
SCRIPT5009: 'jQuery' is undefined 
jquery.gridmanager.min.js, line 4 character 3
SCRIPT1010: Expected identifier 
vendor.d95e00014e9f5f987de8.js, line 9696 character 38
SCRIPT1010: Expected identifier 
app.9d1c0c66c81444982e39.js, line 503 character 10

Test Scenarios
***************
1. Webbuilder Should be Working in IE Browser.

**Comment by emp005169** [comment]
Google Chrome - 49 and above,
Mozilla Firefox - 44 and above,
Microsoft Edge - 41 and above.

**Comment by fsaiyedOB** [comment]
IE is not supported by GrapesJS

**Comment by Nikunj025** [comment]
Due to Limitation of Grapesjs IE Browser does not Supporting.
