### ISSUE TITLE
QA - Website builder - Pages - Image Upload - Broken Image display if User Close Add Image popup without upload any.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#348]
Create Project.
Create One Page in Pages Folder.
Click on That Page.
Click on Basic Section from besides.
Drag Image Componant.
Close Add Image popup without upload any Image.
Observe Broken Image display on Page.

![broken image display if user close add image popup without upload any image](https://user-images.githubusercontent.com/36226408/36190397-0d4a46fc-117e-11e8-864c-0958de94f25e.jpg)

**Comment by fsaiyedOB** [comment]
It will show the broken image as you have not selected any image from modal. If you don't want that, remove that component. Else you can set alt in the settings.

**Comment by acharotariya** [comment]
working..!!
