### ISSUE TITLE
QA - Website builder - Pages - Progress bar - Undefined text display on Preview page if user use Progress bar.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#349]
Create Project.
Create One Page in Pages Folder.
Click on That Page.
Click on Special Componant Section from besides.
Drag Progressbar Componant.
Save page and click on preview button.

![undefined text display on preview page if user use progressbar](https://user-images.githubusercontent.com/36226408/36190409-250c9538-117e-11e8-86cb-6008a7ff0ac0.jpg)

**Comment by fsaiyedOB** [comment]
Add you value for % in progress bar component settings

**Comment by acharotariya** [comment]
Still not resolved.

**Comment by HarshOB** [comment]
Stapes to check :  drag progress bar component -> set value in traits of that component and preview page

**Comment by qajha** [comment]
Issue is resolved now in QA server
