### ISSUE TITLE
QA - Website builder - Pages - Page preview and its CSS are mismatched like its position is not proper.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#350]
Create Project.
Create One Page in Pages Folder.
Click on That Page.
Upload Image For Page Background.
Click on Basic Section from besides.
Drag Image Uploader Componant.
Drag 3 colomn Componant.
Drag Reuse Componant for reuse partial.
Now Save the Page and Click on Preview.
Observe That Page is not display properly.

![page preview and its css are mismatched like its position is not proper 1](https://user-images.githubusercontent.com/36226408/36190424-3d0bfbce-117e-11e8-9f27-56efaa9a11c8.jpg)
![page preview and its css are mismatched like its position is not proper 2](https://user-images.githubusercontent.com/36226408/36190423-3cca8e82-117e-11e8-833f-2e1341958e86.jpg)

**Comment by gkumar9** [comment]
https://github.com/artf/grapesjs/issues/966

**Comment by gkumar9** [comment]
All new website will not face this prob.

**Comment by Nikunj025** [comment]
Still not resolved.
Refer below attachments.

![reopen 1](https://user-images.githubusercontent.com/36226408/37959506-e3a0fba2-31d0-11e8-9ab1-cc725d76e1e7.jpg)
![reopen 2](https://user-images.githubusercontent.com/36226408/37959508-e3cd5864-31d0-11e8-8fe2-b001418bc420.jpg)

**Comment by Nikunj025** [comment]
Done
