### ISSUE TITLE
QA - Website builder - Pages - Image Upload - User can not be able to upload Image From local System.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#351]
Create Project.
Create One Page in Pages Folder.
Click on That Page.
Click on Basic Section from besides.
Drag Image Componant.
Enter Local Path of Image.

![user can not be able to upload image from local system](https://user-images.githubusercontent.com/36226408/36190441-601ff520-117e-11e8-9fae-6421ace1c3e5.jpg)

**Comment by fsaiyedOB** [comment]
To upload local files, goto Project Settings > Asset Images and upload file. This will automatically show in the basic > image component.

**Comment by acharotariya** [comment]
it's working fine.
