### ISSUE TITLE
QA - Website Builder - Page Creation - Page Setting - Decorations - Need to Add Color Picker for Color Setting.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#352]
Create Project.
Create One Page in Pages Folder.
Click on That Page.
Click on Decorations Section from besides.
Go to Background Color and observe that Color Selecton box needs to be there.

![need to add color picker for color setting](https://user-images.githubusercontent.com/36226408/36190456-7430a578-117e-11e8-9beb-d6b7e96221be.jpg)

**Comment by fsaiyedOB** [comment]
Color picker issue with Grapes JS. Will add an issue on their repo.

**Comment by Nikunj025** [comment]
Done

**Comment by qajha** [comment]
Issue is resolved now in QA server
