### ISSUE TITLE
QA - Website Builder - After Uploading Image Page Preview is not Working if Site is not published.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#353]
Create Project.
Create One Page in Pages Folder.
Click on Created Page and add Image Upload Componant From basic Componant.
Choose or Enter Image Path for Image.
Now Click on Preview button of that page.
Observe that after nothing is happened only Page Loading is Continued.

**Comment by fsaiyedOB** [comment]
We have checked in our code. Image component is working fine. We will check after pushing to QA branch.

**Comment by acharotariya** [comment]
it's working fine..!!
