### ISSUE TITLE
QA - website builder - undo & redo shortcut option for keyboard is not work.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#357]
![https www webbuilder qaflowz tk editor 6](https://user-images.githubusercontent.com/28082572/36198317-3cbd9c2c-119c-11e8-8723-bc9d053f2881.png)

**Comment by fsaiyedOB** [comment]
Keyboard shortcuts are not supported.

**Comment by HarshOB** [comment]
Using grapes button you can undo & redo.

**Comment by qajha** [comment]
Issue is closed now as per developer comment
