### ISSUE TITLE
QA - 1 column component - column colour are not reflect properly.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#373]
steps:
1. select 1 column component.
2. change background colour of row class and change paritcular cell background color. ( here give my own class )
![flowz builder the next generation dynamic website builder 2](https://user-images.githubusercontent.com/28082572/36303423-19743da6-1332-11e8-83c2-b353886ceb8e.png)

3. not view component as above changing..
![5a698e87b31f740013e1fdc8 fffa06c5 32a8 44f3 aa02 e694690b15c6 qaflowz tk preview index html](https://user-images.githubusercontent.com/28082572/36303319-bf775676-1331-11e8-93d4-0c0bed2bdf76.png)

**Comment by fsaiyedOB** [comment]
Same as #350

**Comment by fsaiyedOB** [comment]
While using any component, add your custom class in properties and then add custom styles.

**Comment by Nikunj025** [comment]
Done
