### ISSUE TITLE
QA - suggestion - class is deleted than can not perform undo action or no reset option for reset changing value on particular class.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#374]
![flowz builder the next generation dynamic website builder 4](https://user-images.githubusercontent.com/28082572/36304152-94b75bae-1334-11e8-904f-f44c672f992f.png)

**Comment by HarshOB** [comment]
We can't prevent the user from deleting that classes.

**Comment by fsaiyedOB** [comment]
Feature not supported by [GrapesJS](https://github.com/artf/grapesjs)
