### ISSUE TITLE
QA-CRM-Subscription Plan-When we create the Plan and subscribed it and then go to Website builder and create the website then system is showing Error "Permission not available for action" 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#378]
When we create the Plan and subscribed it and then go to Website builder and create the website then system is showing Error "Permission not available for action"

1.Create the Plan
2.Buy the Plan Dev Dev QA Plan
3.Go to Website Builder
4.Create the website
--

**Comment by mohit5540** [comment]
Please check webbuilder/project-configure count or required permission in webbuilder for admin role in acl.

**Comment by qajha** [comment]
Ok We will check this Issue when ACL functionality is working fine.

**Comment by qajha** [comment]
Issue is working fine in QA server
