### ISSUE TITLE
QA - default header partial are overidded in default template.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#381]
create new website with default layout.
publish and see the webiste preview.
but here default header partial option is overidded with existing template navbar.you have to make as it is or just removed it...so default template visible as it is without any changes.

![5a698e87b31f740013e1fdc8 048cc6e1 6114 47ce 8665 577c0e7c0c9e qaflowz tk 6](https://user-images.githubusercontent.com/28082572/36377996-14bc0bf8-159f-11e8-9ae9-05e8cde5cad6.png)

**Comment by mohit5540** [comment]
please select blank layout for header/footer in such cases.

**Comment by qajha** [comment]
Issue is resolved now in QA server
