### ISSUE TITLE
QA - Website Builder - Project name already exist error display even if that project is not available.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#384]
QA - Website Builder - Project name already exist error display even if that project is not available.

Create New Project.
Now try to rename it.
user can not be able to update their project name and found error "project is already there.

![project name already exist error display even if that project is not availabe](https://user-images.githubusercontent.com/36226408/36463189-4378f654-16ee-11e8-95bb-21b776684b6d.jpg)

**Comment by gkumar9** [comment]
Possibly you might have created a website of name "Firstproject" in another subscription plan. Can you check and confirm??

**Comment by HarshOB** [comment]
There is already Firstporject website under 3968f-QA-GoldenPlan[Confirmed in DB]. So, it gives an error.

**Comment by acharotariya** [comment]
Without Refresh Page Project Name is not Updating in Sidebar, so user get confused if its project name is changed or not ???

**Comment by qajha** [comment]
Issue is resolved now in QA server
