### ISSUE TITLE
QA - Website builder - Sign up Page - Email Format should be validate on registration or sign up page.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#386]
QA - Website builder - Sign up Page - Email Format should be validate on registration or sign up page.

right now its allow any data without formation.

![email format should be validate on registration or sign up page](https://user-images.githubusercontent.com/36226408/36464631-e415a8e8-16f6-11e8-9fd7-a25ded4372cd.jpg)

**Comment by fsaiyedOB** [comment]
Added email pattern verification

**Comment by qajha** [comment]
Issue is working fine in QA server
