### ISSUE TITLE
QA - Website Builder - Validation Message is not proper if user try to create project without selecting any subscription.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#387]
QA - Website Builder - Validation Message is not proper if user try to create project without selecting any subscription.

User should not be allowed perform any action if that user has no subscription.
suggestion : All the actions should be disable till user should not select his subscriptions.

![user should not be allowed perform any action if that user has no subscription](https://user-images.githubusercontent.com/36226408/36521909-82f05e86-17bf-11e8-996c-d30cf24abefd.jpg)

**Comment by gkumar9** [comment]
If no subcription is selected then message shown such as foloowing:
![screenshot from 2018-02-23 15-30-54](https://user-images.githubusercontent.com/33317261/36588593-a0b28616-18ae-11e8-839e-6b7fe19b2b96.png)

**Comment by qajha** [comment]
Issue is resolved now in QA server
