### ISSUE TITLE
QA - Website Builder - Site is not working in Firefox Lower Version.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#389]
QA - Website Builder - Site is not working in Firefox Lower Version.

After hit on url only White Blank page is display.

![site not working in lower version of firefox](https://user-images.githubusercontent.com/28082572/36471813-d6ec1412-1715-11e8-8729-08c997d5a1db.jpg)

Test Scenarios
***************
1. System should be working from discussed Firefox versions.

**Comment by mohit5540** [comment]
Lower version does not support promise and other features. Please mention which features are not working.

**Comment by qajha** [comment]
Right now the website is not working in firefox version 43 so please just tell at baseline of versioning. firefox and chrome browser.

**Comment by fsaiyedOB** [comment]
Currently, minimum FireFox support is 44 and up

**Comment by Nikunj025** [comment]
Done.

Webbuilder is working Fine up to above mentioned version.
