### ISSUE TITLE
QA - Website Builder - Validation Message is not proper when user Enter Wrong LDAP Credentials.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#390]
QA - Website Builder - Validation Message is not proper when user Enter Wrong LDAP Credentials.

![validation message is not proper when user try login with ldap](https://user-images.githubusercontent.com/36226408/36472058-8ad67f08-1716-11e8-87fd-22392081729f.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
