### ISSUE TITLE
QA-Website Builder-Invite-when user login into Website builder dashboard and not invite any user but system is showing the all data in Assigned History.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#391]
When user login into Website builder dashboard and not invite any user but system is showing the all data in Assigned History.

**Comment by HarshOB** [comment]
Can you please check the DB? because there might be previous data for that user. Delete that data and try again.

**Comment by qajha** [comment]
but when I create the new user and login into Dashboard and go to website builder and check assigned history showing one details for new user login.

**Comment by fsaiyedOB** [comment]
Checked with the new user and logging in. In invite>assignedHistory not showing any data.

**Comment by qajha** [comment]
Issue is resolved now in QA server

**Comment by qajha** [comment]
Problem again with new user:::


![assigned history issue](https://user-images.githubusercontent.com/36195435/36639709-b00cd388-1a38-11e8-917b-34e4b97fe767.png)

**Comment by qajha** [comment]
Issue is resolved now in QA server
