### ISSUE TITLE
QA-Website Builder-Dashbaord-When no Assigned Subscription is there but application is showing "暂无数据" in list view.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#392]
When no Assigned Subscription is there but application is showing "暂无数据" in list view.
![assigned subscription](https://user-images.githubusercontent.com/36195435/36475439-a7f0614e-1720-11e8-82ad-6f5fdcee3b82.png)

**Comment by HarshOB** [comment]
resolved.

**Comment by qajha** [comment]
Issue is resolved now in QA server
