### ISSUE TITLE
QA - Website Builder - Default Publish Functionality is not working.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#434]
QA - Website Builder - Default Publish Functionality is not working.

Create New project.
Apply Template 2 from Import Plugins and click on Refresh Button.
Click on Default Publish from Project Setting.

Page only loads but nothing will happen and we getting errors.

![default publish functionality is not working](https://user-images.githubusercontent.com/36226408/36626623-0cc4a5f2-195c-11e8-8d36-b0fb3d20f740.jpg)

**Comment by qajha** [comment]
Closed this Issue
