### ISSUE TITLE
QA-Website Builder-Project Settting-Download zip functionality is not working fine in commit project feature

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#435]
404

The page could not be found or you don't have permission to view it.

The resource that you are attempting to access does not exist or you don't have the necessary permissions to view it.

Make sure the address is correct and that the page hasn't moved.

Please contact your GitLab administrator if you think this is a mistake.

**Comment by qajha** [comment]
404

The page could not be found or you don't have permission to view it.

The resource that you are attempting to access does not exist or you don't have the necessary permissions to view it.

Make sure the address is correct and that the page hasn't moved.

Please contact your GitLab administrator if you think this is a mistake.

**Comment by fsaiyedOB** [comment]
Now user is able to download project zip file

**Comment by qajha** [comment]
Still same Issue is comes and user not download the Zip file

**Comment by qajha** [comment]
Issue is resolved now in QA server
