### ISSUE TITLE
QA - page section - getting full path instead of filename when creating new page.

### ISSUE THREAD

**Issue by acharotariya** [FlowzPlatform/website-builder#436]
go to page section
create new page (my.html)
getting full path instead of filename.
![flowz builder the next generation dynamic website builder 6](https://user-images.githubusercontent.com/28082572/36626787-dd55021e-195e-11e8-9593-06930575b9af.png)

**Comment by qajha** [comment]
Right now this Issue is reproducible so I have closed this Issue..
