### ISSUE TITLE
QA - Website builder - Website clone functionality is not working.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#453]
Website clone functionality is not working.

We are waiting till 20 mins but its not complete their process and gives error in Inspect Element.

![cloning functionality is not working](https://user-images.githubusercontent.com/36226408/36639150-0637c752-1a2c-11e8-84a5-6520ea07586b.jpg)

**Comment by qajha** [comment]
Issue is resolved now in QA server
