### ISSUE TITLE
QA - Website builder - Full Server path getting in tooltip.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#454]
QA - Website builder - Full Server path getting in tooltip.

![full server path getting in tooltip](https://user-images.githubusercontent.com/36226408/36639486-cb22eb44-1a33-11e8-953f-23be563bd817.jpg)

**Comment by HarshOB** [comment]
Tabs is removed as of now

**Comment by gkumar9** [comment]
Removed tabs.
