### ISSUE TITLE
QA - Website Builder - If user try to login with Social Media then page should be open in new tab or new window.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#455]
QA - Website Builder - If user try to login with Social Media then page should be open in new tab or new window.

Test Scenarios
***************
 1. When User try to login with Social Media then Page should be redirect to next tab.

**Comment by mohit5540** [comment]
Social login is managed with centralized api. Please confirm with @acharotariya / @npaulOB  .

**Comment by Nikunj025** [comment]
As Per Discussion it should not be redirect to next tab but its redirect to our product after login in Same tab.
