### ISSUE TITLE
QA - Website Builder - After login into website builder, user can not be see its username or email id on dashboard.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#456]
QA - Website Builder - After login into website builder, user can not be see its username or email id on dashboard.

![after login into website builder user can not be see its username or email id on dashboard](https://user-images.githubusercontent.com/36226408/36639670-01e474b4-1a38-11e8-89aa-e19f4e5329a1.jpg)

**Comment by qajha** [comment]
Done.
username is display in tooltip when user is Mouse hover on logout button.
