### ISSUE TITLE
QA - Website Builder - Error msg display on create project popup without click on create project button.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#459]
QA - Website Builder - Error msg display on create project popup without click on create project button.

Login with Cred.
Click on Create Project option.
now close the create project popup.
Click on Create Project option again.
Observe popup open with validation message.

![error msg display on create project popup](https://user-images.githubusercontent.com/36226408/36639900-d3ae58fe-1a3b-11e8-9079-2b903602647c.jpg)

**Comment by qajha** [comment]
Done. Its working fine on QA Server.
