### ISSUE TITLE
QA-Website builder-When user invite the user for some role and select the new subscription in dropdown list and click on Invite new button system is showing Token Error message Refer Attachment 

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#460]
![first time using subscription](https://user-images.githubusercontent.com/36195435/36639976-73c23cd8-1a3d-11e8-8846-511ce65b44f7.png)

**Comment by HarshOB** [comment]
As we discussed @qajha this scenario is no longer present in the current phase.

**Comment by qajha** [comment]
Issue is resolved now in qa server
