### ISSUE TITLE
QA - Website Builder - After revert project revision data still showing in list section.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#461]
QA - Website Builder - After revert project revision data still showing in list section.

![after revert project revision data still showing in list section](https://user-images.githubusercontent.com/36226408/36640222-88cfc85e-1a40-11e8-9114-dc15b9f8b519.jpg)

**Comment by fsaiyedOB** [comment]
Project configuration data needs to be added in revisions.

**Comment by fsaiyedOB** [comment]
Issue related to #464

**Comment by qajha** [comment]
Issue is resolved now in QA server
