### ISSUE TITLE
QA - Website Builder - Commit and revert - When User Commit their revision then system should not be published automatically.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#463]
QA - Website Builder - Commit and revert - When User Commit their revision then system should not be published automatically without user permission.

There are two success message are displayed.

![revision and comission](https://user-images.githubusercontent.com/36226408/36640422-5c86692a-1a44-11e8-83f8-217ade7f4f54.jpg)

.

**Comment by fsaiyedOB** [comment]
The message needed to be updated. Updated the message.

**Comment by qajha** [comment]
Issue is resolved now in QA server
