### ISSUE TITLE
QA-Website Builder-Project Setting-Revert commit is not working properly if we have using the existing template

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#464]
When user create the project and then Initial push is showing in commit section and the user using the existing templates and add the new commit for those existing template and publish the website and after then we have restored the initial and then publish the website system is showing "Internal Server Error"
![revert issue](https://user-images.githubusercontent.com/36195435/36640660-62fd30c2-1a49-11e8-9879-89218d78aad9.png)

Test Scenarios
***************
1. System should accept the changes made in the existing template and should save.
2. If user select new template then all the changes should be saved.

**Comment by fsaiyedOB** [comment]
Project configuration data needs to be added in revisions.

**Comment by qajha** [comment]
Issue is not working properly ,when we create the website and take the intial push and take the existing template and published it after some time user revet the rev to intial push and published it and revert the exisiting template website in that case only one file is showing in page section not all website page.

**Comment by Nikunj025** [comment]
Done
