### ISSUE TITLE
QA - Website Builder - Global Variable - Broken Image display when user upload local image.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#481]
QA - Website Builder - Global Variable - Broken Image display when user upload local image.

![broken image display when user upload local image](https://user-images.githubusercontent.com/36195435/36670960-05d4ad94-1b20-11e8-945e-c0506bea3747.jpg)

**Comment by fsaiyedOB** [comment]
Replaced normal image uploader with FileStack uploader

Issue is resolved

**Comment by qajha** [comment]
Issue is resolved now in QA server
