### ISSUE TITLE
QA-Website Builder-When I login into website builder and create the website and after some time the website creation icon is showing in two times refer Attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#485]
![website icon showing](https://user-images.githubusercontent.com/36195435/36730994-59eebbb6-1bef-11e8-8a23-7ebb6f3c38d3.png)

**Comment by fsaiyedOB** [comment]
Duplicate #278

**Comment by qajha** [comment]
I have closed this ticket but open ticket:
