### ISSUE TITLE
QA-Website builder-When user create the Vshop id in distributor link and save the vshop id in Website settings and if user delete the record from distributor link then system still showing id in place holder.refer attachment

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#514]
![vshop id](https://user-images.githubusercontent.com/36195435/37152989-3fc9369e-2301-11e8-8412-5329303cad70.png)

**Comment by gkumar9** [comment]
https://github.com/FlowzPlatform/website-builder/commit/b277447176e5d3a5ab0bab3252e8434a74c8a9f2
solved in this commit.

**Comment by qajha** [comment]
Issue is resolved now in QA server
