### ISSUE TITLE
QA - User id, pwd and esuser data missing sometimes in Projectvid Setting after website published.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#516]
QA - User id, pwd and esuser data missing sometimes in Projectvid Setting after website published.

![user id pwd and esuser field is missing](https://user-images.githubusercontent.com/36195435/37192958-fc1e59c8-238d-11e8-80c9-f1adaa361e3d.jpg)

**Comment by gkumar9** [comment]
wrong issue number in commit its #514

**Comment by Nikunj025** [comment]
Done.

Data will be available after Select VShop Id and Save it.
