### ISSUE TITLE
QA - Website Builder - Page is not responding in Browser If User Click on Published Website if Logout Popup is Occur.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#518]
QA - Website Builder - Page is not responding in Browser If User Click on Published Website if Logout Popup is Occur.

Suggestion - if user is logout then it should not be allow to click on any page object.

![this site can not be reached](https://user-images.githubusercontent.com/36195435/37193843-81a2b424-2391-11e8-9663-9bc8e7337dd5.jpg)

**Comment by fsaiyedOB** [comment]
Logout is handled.

**Comment by qajha** [comment]
Issue is resolved now in QA server

**Comment by Nikunj025** [comment]
Still Site not Published Yet Page Display Sometimes.

**Comment by Nikunj025** [comment]
Done
