### ISSUE TITLE
QA - Website Builder - Service unavailable Message display if user logout and login from other module

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#519]
QA - Website Builder - Service unavailable Message display if user logout and login from other module.

When user publish the website and meanwhile CRM open in another tab then user decided to logout from CRM and come back in website builder,  system is progress the publish the website.

Now User Login with Same Cred in CRM and Go to Website Builder then System display error "Service Unavailable.

![service unavailable message display if user logout and login from other module](https://user-images.githubusercontent.com/36195435/37194046-63405e68-2392-11e8-9a48-269ab2a98504.jpg)

**Comment by fsaiyedOB** [comment]
Logout is handled.

**Comment by Nikunj025** [comment]
Still Not Resolved.
Discussed with Mohit Shah.

**Comment by Nikunj025** [comment]
Done
