### ISSUE TITLE
QA -Website Builder - During the Publishing Site if User is logout from the System then System is publishing Half Site. It Should not.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#535]
QA -Website Builder - During the Publishing Site if User is logout from the System then System Should not be allowed Published Half Site.

**Comment by fsaiyedOB** [comment]
This will be resolved once Joq Queue is implemented in the next sprint.

**Comment by emp005169** [comment]
will be solved with metalsmith publish jobqueue feature implementation.

**Comment by emp005169** [comment]
keep label as suggestion/improvement. as already commented - will be solved with metalsmith publish jobqueue feature implementation.

**Comment by gkumar9** [comment]
Done and moved to staging.
