### ISSUE TITLE
QA - Website Builder - Pages - Page Setting - Image Preview is not Proper for Favicon icon.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#538]
QA - Website Builder - Pages - Page Setting - Image Preview is not Proper for Favicon icon.

![image preview is not proper for favicon icon](https://user-images.githubusercontent.com/36226408/37584051-ea299036-2b79-11e8-8d31-54816494dce2.jpg)

**Comment by Nikunj025** [comment]
Preview Image is missing now pls check once.

**Comment by fsaiyedOB** [comment]
There is no Image preview available. It was just a font glitch.

**Comment by Nikunj025** [comment]
Its Working Fine.
We display only Image Name not Image Preview.
