### ISSUE TITLE
QA -Suggestion - Website Builder - Favicon icon size should be validate on Save Setting buttons.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#540]
QA -Suggestion - Website Builder - Favicon icon size should be validate on Save Setting buttons.

**Comment by Nikunj025** [comment]
Still not resolved and 70 KB Image should be acceptable as per Comment. but its not Accept 70 KB Image.

**Comment by gkumar9** [comment]
Images with PNG and ICO formats within 70kb are valid images.

**Comment by Nikunj025** [comment]
Still user can not be able to upload 70 KB Images for Favicon icon.

Try with below Image its size is 69.5 KB, Stii User can not be able to upload that image as Favicon icon.

[Favicon.zip](https://github.com/FlowzPlatform/website-builder/files/1874929/Favicon.zip)

**Comment by fsaiyedOB** [comment]
Favicon upload is now updated. Max file size upload is 67kb.
[1515976514323.png.zip](https://github.com/FlowzPlatform/website-builder/files/1875092/1515976514323.png.zip)

**Comment by Nikunj025** [comment]
Still User Can not able to upload file.

When User try to upload 67 kb file, its not uploaded.

try with below Zip for reference.

[67kb.zip](https://github.com/FlowzPlatform/website-builder/files/1878722/67kb.zip)

**Comment by Nikunj025** [comment]
Done
