### ISSUE TITLE
QA - Website Builder - If User is not Active on WebPage after Login into Website Builder then After Some Times There is One Project is Automatically display in sidebar without Name.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#558]
QA - Website Builder - If User is not Active on Web Page after Login into Website Builder then After Some Times There is One Project is Automatically display in sidebar without Name.
After Refresh The Page that will be disappear.

![website without name](https://user-images.githubusercontent.com/36226408/37949426-3fb7390c-31b2-11e8-967e-67d8b7281ad7.jpg)

Test Scenarios
***************
1. If User Should be not active on webpage, then Session Should be Expire Automatically.
2. User Should be redirect on Login Page if user are not active on webpage.

**Comment by Nikunj025** [comment]
Issue still persists if user logged in from two or more than two different system and working with Same User.

**Comment by fsaiyedOB** [comment]
Resolved.
