### ISSUE TITLE
QA - Website Builder - Only One Success Message needs to display in Page Setting when User apply bootstrap CSS.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#566]
QA - Website Builder - Only One Success Message needs to display in Page Setting when User apply bootstrap CSS.

![alert message](https://user-images.githubusercontent.com/36226408/38014785-74ba1cd4-3287-11e8-8be8-73b271da9f4e.jpg)

**Comment by fsaiyedOB** [comment]
This is not related to Bootstrap selection. You have not selected any Header and Footer partial. So partial is auto set to default.

**Comment by Nikunj025** [comment]
As Per your Comment, Both Messages are display Correct.
one for the Header partial and another is Footer partial.
