### ISSUE TITLE
Implement Tabs for opened files.

### ISSUE THREAD

**Issue by fsaiyedOB** [FlowzPlatform/website-builder#8]
Using Tabs component from ElementUI, implement feature  that will open file when clicked through SideMenu in a new Tab. When user closes the tab containing unsaved changes, user will be asked to save those changes or not.

**Comment by KrishnaPG** [comment]
Tab order should be remembered in `local storage`.

Options:

1. Use https://github.com/y-js/yjs to sync content across tabs and different browsers
2.  Use https://github.com/Irrelon/ForerunnerDB for more simpler localstorage saving option
